# Generated by Django 5.1.5 on 2025-02-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gostem', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contentType', models.CharField(default=None, max_length=50)),
                ('authorName', models.CharField(default=None, max_length=100)),
                ('event', models.CharField(default=None, max_length=100)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_notes', to='gostem.user')),
                ('programName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostem.program')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
